### ISSUE TITLE
The Z-value in the mann_kendall.m is incorrect when S>=0

### ISSUE THREAD

**Issue by zhiyingli-geo** [chadagreene/CDT#10]
ind = S>=0; 
Line 121: Z(ind) = ((S(ind)-1)/StdS).*(S(ind)); 
should be: Z(ind) = ((S(ind)-1)/StdS).*(S~=0);

The (S(ind)) is only correct when ind = logical 0. When ind = logical 1, Z(ind) = ((S(ind)-1)/StdS).*(S(ind)) = ((S(ind)-1)/StdS).*S. This is incorrect.

**Comment by chadagreene** [comment]
@lzy2937 You are exactly right. The bug has been fixed. Thank you so much for tracking down this error!

**Comment by zhiyingli-geo** [comment]
Thank you for fixing it!
