### ISSUE TITLE
A Chinese version of CDT Contents 

### ISSUE THREAD

**Issue by tfoterye** [chadagreene/CDT#14]
[CDT 中文翻译.pdf](https://github.com/chadagreene/CDT/files/6985814/CDT.pdf)
I'm using CDT and I'm exciting about finding such a terrific toolbox for processing meteorology data. However as I'm a Chinese, some of my colleagues or classmates cannot understand the wiki and instruction exactly. So I translate the CDT Contents (mostly from https://www.chadagreene.com/CDT/CDT_Contents.html ) into Chinese. 
The work has been started about 5 months ago.  Due to my personal reasons, I feel very ashamed of delaying the process of translation. Last week, I translated and typeset all the function documents of the toolbox, which took a long time longer than expected. This is the PDF version after typesetting. I'm not sure if there will be any errors in it. Please review it if convenient.
I hope it may help other people when using this toolbox.

**Comment by chadagreene** [comment]
@tfoterye That's fantastic! Very impressive effort. I've linked to the pdf in the README on the main page. Thanks for all your work.

**Comment by tfoterye** [comment]
Thanks for ur link and hope more work could be done with my effort.
