### ISSUE TITLE
sw_pden calls non-existent functions

### ISSUE THREAD

**Issue by JakeWeis** [chadagreene/CDT#16]
`sw_pden` in `mld` calls two non-existent functions `sw_ptmp` and `sw_dens`.

**Comment by Mikhil11** [comment]
the two functions exists you can find them in the below link
https://github.com/OceanMixingGroup/mixingsoftware/tree/master/seawater

**Comment by chadagreene** [comment]
@JakeWeis Thanks for letting me know! 

@kakearney do you have a preferred fix for this? It looks like `sw_pden` is in the private folder. Should we add `sw_ptmp` and `sw_des` to the private folder too, or make them subfunctions of `sw_pden`?

**Comment by kakearney** [comment]
Oops, sorry for overlooking those dependencies!

These functions are all part of CSIRO's SeaWater EOS-80 toolbox (v3.2).  Given that they are part of a third-party toolbox, I'd like to keep the functions in their original separate form, so as a short-term solution, I'll go ahead and add those extra files to the private folder.

However, the EOS-80 standard is now obsolete, having been superseded by the TEOS-10 standard.  I've been lazy about updating my code to use the latter standard (and its associated [Gibbs SeaWater Oceanographic Toolbox](https://www.teos-10.org/software.htm) functions), but I'll try to do that ASAP for this function.

**Comment by JakeWeis** [comment]
Thanks! There are further missing dependencies in `sw_ptmp` (`sw_adtg`) and `sw_dens` (`sw_seck` and `sw_dens0`).

**Comment by kakearney** [comment]
I think I got 'em all now (all the above plus `sw_smow`).

**Comment by chadagreene** [comment]
Thanks @kakearney! Can we close this issue?

**Comment by kakearney** [comment]
Yes, closing it now.
