### ISSUE TITLE
Incorrect masks generated for specific cases of 2Drange

### ISSUE THREAD

**Issue by ccasadio** [chadagreene/CDT#2]
If coordinates on a `0 to 360` grid cross `180` then the resulting mask will nearly be the inverse of the intended mask. The reason for this is because of the combination of changing to a `-180 to 180` coordinate system and the assumption that the smaller longitude is the leftmost and larger rightmost (lines referenced below).

https://github.com/chadagreene/CDT/blob/88389037acf6fb630a9611801697e34f562e459b/cdt/geomask.m#L95-L99

https://github.com/chadagreene/CDT/blob/88389037acf6fb630a9611801697e34f562e459b/cdt/geomask.m#L141

EX (simplified to 1d):
`lon =   [0 60 120 180 240 300];`
`lonv = [100 250];`

the expected mask is 
`[0 0 1 1 0 0]`

both inputs would be changed to `-180 to 180`  coordinate system
`lon =   [0 60 120 180 -120 -60];`
`lonv = [100 -110];`

`min(lonv)` is now `-110` instead of `100` and `lon>min(lonv)` would produce
 `[1 1 1 1 0 1]`
and `lon<max(lonv)` would produce
`[1 1 0 0 1 1]`
the logical and of these 2 produces
`[1 1 0 0 0 1]`

I propose assuming the first value of lonv is the leftmost input. This would be more in line with how someone would read the value and find it on a globe.

`if lonv(1) > lonv(2)`
    `mask = lat>min(latv) & lat<max(latv) & (lon>lonv(1) | lon<lonv(2));`
`else`
    `mask = lat>min(latv) & lat<max(latv) & (lon>lonv(1) & lon<lonv(2));`
`end`

**Comment by chadagreene** [comment]
Thanks @ccasadio for bringing this up, and thanks for explaining the issue so clearly. I think I've fixed it now, but let me know if I overlooked anything.

**Comment by ccasadio** [comment]
Looks good to me
