### ISSUE TITLE
MLD calculation mismatch

### ISSUE THREAD

**Issue by JorahLee** [chadagreene/CDT#6]
Appreciate your work! It's a useful toolbox!
In mld.m profile, IN-SITU temperature is inputted. However, to calculate potential density, the code refers to gsw_rho, in which the input arguments are CONSERVATIVE temperature (or potential temperature) and ABSOLUTE SALINITY (g/kg). The unit of salinity is not illustrated in the header lines. The difference in the type of temperature and an uncommon salinity unit could lead to a serious mistake. Simply change gsw_rho to sw_pden would do the trick. :p
ps: There's a typo on https://www.chadagreene.com/CDT/mld_documentation.html. The examples adopt a T threshold of 0.2 deg C, yet it's changed to 0.02 deg in the code below.

**Comment by chadagreene** [comment]
@JorahLee Sorry about the egregious delay, but thanks for the note. Maybe @kakearney can comment on this?

**Comment by kakearney** [comment]
Thanks for the feedback, @JorahLee.  You're correct that I got a bit lazy with units, both in my use of the gsw_rho function, and in the documentation of the exact units on the function inputs.  Reviewing the Holte et al., 2009 paper, the original Argo-based algorithm referenced in-situ temperature, practical salinity, and potential density.

The easiest fix for the potential density calculation, as noted by @JorahLee, is to use the seawater toolbox sw_pden function. We *could* do the conversion with the GSW toolbox, but that involves at least 3 conversion steps and introduces lat/lon to the mix... which may be technically more accurate and correct according to TEOS-10 standards, but is probably overkill for this algorithm.  I can make that change and add sw_pden to the CDT private folder; @chadagreene, does this sound good to you?

**Comment by chadagreene** [comment]
Absolutely, @kakearney, you're the expert here, so do whatever you think is best.

**Comment by kakearney** [comment]
Resolved via 9e12a700d15078e695c0dbe769738d4179253505
